import { v4 as uuidv4 } from 'uuid';

interface PageData {
    title: string;
    slug: string;
    content?: string;
    template?: string;
}

/**
 * Generates a WXR (WordPress eXtended RSS) file content.
 * This allow users to import the generated pages into WordPress via Tools > Import.
 */
export function generateWXR(pages: PageData[]): string {
    const date = new Date().toISOString().replace('T', ' ').split('.')[0];

    let items = '';

    pages.forEach((page, index) => {
        const id = 100 + index;
        items += `
    <item>
        <title>${page.title}</title>
        <link>http://localhost/?page_id=${id}</link>
        <pubDate>${new Date().toUTCString()}</pubDate>
        <dc:creator><![CDATA[admin]]></dc:creator>
        <guid isPermaLink="false">http://localhost/?page_id=${id}</guid>
        <description></description>
        <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Page generated by Press Stack.</p>
<!-- /wp:paragraph -->]]></content:encoded>
        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
        <wp:post_id>${id}</wp:post_id>
        <wp:post_date><![CDATA[${date}]]></wp:post_date>
        <wp:post_date_gmt><![CDATA[${date}]]></wp:post_date_gmt>
        <wp:comment_status><![CDATA[closed]]></wp:comment_status>
        <wp:ping_status><![CDATA[closed]]></wp:ping_status>
        <wp:post_name><![CDATA[${page.slug}]]></wp:post_name>
        <wp:status><![CDATA[publish]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type><![CDATA[page]]></wp:post_type>
        <wp:post_password><![CDATA[]]></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
        ${page.template ? `
        <wp:postmeta>
            <wp:meta_key><![CDATA[_wp_page_template]]></wp:meta_key>
            <wp:meta_value><![CDATA[${page.template}]]></wp:meta_value>
        </wp:postmeta>` : ''}
    </item>
`;
    });

    return `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/"
>
<channel>
    <title>Press Stack Export</title>
    <link>http://localhost</link>
    <description>Export from Press Stack</description>
    <pubDate>${new Date().toUTCString()}</pubDate>
    <language>en-US</language>
    <wp:wxr_version>1.2</wp:wxr_version>
    <wp:base_site_url>http://localhost</wp:base_site_url>
    <wp:base_blog_url>http://localhost</wp:base_blog_url>

    ${items}
</channel>
</rss>`;
}
