import archiver from 'archiver';
import { PassThrough } from 'stream';

export const generateZip = async (phpContent: string, acfJSON: any, templateName: string): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const bufs: Buffer[] = [];
        const stream = new PassThrough();

        stream.on('data', (d) => bufs.push(d));
        stream.on('end', () => resolve(Buffer.concat(bufs)));
        stream.on('error', (e) => reject(e));

        const archive = archiver('zip', {
            zlib: { level: 9 }
        });

        archive.on('error', (err) => {
            reject(err);
        });

        archive.pipe(stream);

        // Add PHP Template with dynamic name
        archive.append(phpContent, { name: `${templateName}.php` });

        // Add ACF JSON
        archive.append(JSON.stringify(acfJSON, null, 2), { name: 'acf-json/group_generated.json' });

        // Add README
        const readmeContent = `WordPress Static to Dynamic Conversion Guide
==========================================

Package: ${templateName}

1. Install Advanced Custom Fields (ACF) PRO or Free.
2. Go to Custom Fields > Tools > Import Field Groups.
3. Select 'acf-json/group_generated.json' from this package.
4. Move '${templateName}.php' to your active theme directory.
5. Create a new Page in WordPress.
6. Under 'Page Attributes' or 'Template' settings, select '${templateName}'.
7. Fill in the ACF fields with your content.

Generated by Static to Dynamic Tool.
`;
        archive.append(readmeContent, { name: 'README.txt' });

        archive.finalize();
    });
};
